// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmyofethvzjbcldzikyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNteW9mZXRodnpqYmNsZHppa3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzODczNDQsImV4cCI6MjA4NTk2MzM0NH0.t7sRiUCyUMH93eVWp5VjzwR8yeVQkBPRwWqkVEguoGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});